developers = ["casasriscos.com","altozano.com.mx","virreyesresidencial.com","grupovelas.com.mx","udens.mx","altanaqueretaro","ara.com.mx","urbanamexico.com.mx","cottonovo.com","koloria.com.mx","realdelcimatario.com.mx","sadasi.com","alannaresidencial.com.mx","casastrio.mx","ruba.com.mx","casasperdura.com","comebi.mx","grupocorintio.com","vitaliaresidencias.mx","sonetoresidencial.com","vinte.com.mx","altanaqueretaro.com","oasisazcapotzalco.com","cocoa100veinte.com","miradiamante.com","grupo-gl.com","montebellotowers.com","casassan.com.mx","alcedaresidencial.com","habi.com.mx","casascomebi.mx","sadalpuebla.com","comviveloscedros.com","casasamp.com","alanjo.com.mx","parkview.mx","viveesmeralda.com","ellagoresidencial.mx","reservaescondida.mx","centroc.mx","delbosqueluxurycondos.com","casaspalenque.com","javer.com.mx","residencialsecoya.com","nahresidencial.com","puntacascatta.com","pmetropolis.mx","grupoproyecta.com","todopueblabienesraices.com","nivelunoconstructora.com","pedregalresidencial.com","begrand.mx","htelite.mx","arquitectoma.com","cumbresresidencial.mx","larescapital.com.mx","arcadiatower.mx","grupolaporta.com","nidum.com.mx","plate.mx","constructorakunem.com","casasysoluciones.com","zona04.com","linden.com.mx","covinsa.com","grupoune.com.mx","periferico180.com","vivefuentes.com.mx","gmcapital.com.mx","magmatowers.com.mx","bosquesresidencial.com.mx","www.vivevertical.com","huastecas.com","lashuastecas.mx","birlok.com","ideka.com.mx","abelladesarrollos.com","torrealta.org","cumbrescondido.com","behome.mx","colinasdelvalle.com.mx","trazzo.com.mx"]

developers.each{|domain| domain.prepend("marketing@")}

marketing@casasriscos.com
marketing@altozano.com.mx
marketing@virreyesresidencial.com
marketing@grupovelas.com.mx
marketing@udens.mx
marketing@altanaqueretaro
marketing@ara.com.mx
marketing@urbanamexico.com.mx
marketing@cottonovo.com
marketing@koloria.com.mx
marketing@realdelcimatario.com.mx
marketing@sadasi.com
marketing@alannaresidencial.com.mx
marketing@casastrio.mx
marketing@ruba.com.mx
marketing@casasperdura.com
marketing@comebi.mx
marketing@grupocorintio.com
marketing@vitaliaresidencias.mx
marketing@sonetoresidencial.com
marketing@vinte.com.mx
marketing@altanaqueretaro.com
marketing@oasisazcapotzalco.com
marketing@cocoa100veinte.com
marketing@miradiamante.com
marketing@grupo-gl.com
marketing@montebellotowers.com
marketing@casassan.com.mx
marketing@alcedaresidencial.com
marketing@habi.com.mx
marketing@casascomebi.mx
marketing@sadalpuebla.com
marketing@comviveloscedros.com
marketing@casasamp.com
marketing@alanjo.com.mx
marketing@parkview.mx
marketing@viveesmeralda.com
marketing@ellagoresidencial.mx
marketing@reservaescondida.mx
marketing@centroc.mx
marketing@delbosqueluxurycondos.com
marketing@casaspalenque.com
marketing@javer.com.mx
marketing@residencialsecoya.com
marketing@nahresidencial.com
marketing@puntacascatta.com
marketing@pmetropolis.mx
marketing@grupoproyecta.com
marketing@todopueblabienesraices.com
marketing@nivelunoconstructora.com
marketing@pedregalresidencial.com
marketing@begrand.mx
marketing@htelite.mx
marketing@arquitectoma.com
marketing@cumbresresidencial.mx
marketing@larescapital.com.mx
marketing@arcadiatower.mx
marketing@grupolaporta.com
marketing@nidum.com.mx
marketing@plate.mx
marketing@constructorakunem.com
marketing@casasysoluciones.com
marketing@zona04.com
marketing@linden.com.mx
marketing@covinsa.com
marketing@grupoune.com.mx
marketing@periferico180.com
marketing@vivefuentes.com.mx
marketing@gmcapital.com.mx
marketing@magmatowers.com.mx
marketing@bosquesresidencial.com.mx
marketing@www.vivevertical.com
marketing@huastecas.com
marketing@lashuastecas.mx
marketing@birlok.com
marketing@ideka.com.mx
marketing@abelladesarrollos.com
marketing@torrealta.org
marketing@cumbrescondido.com
marketing@behome.mx
marketing@colinasdelvalle.com.mx
marketing@trazzo.com.mx